### ISSUE TITLE
Not loading after login

### ISSUE THREAD

**Issue by cebem1nt** [cococry/ragnar#45]
**Describe the bug**
Hi, I've installed Ragnar on Arch by installation script in readme. After that, I've configure the config file with the my monitor info, rebooted, tried to login to Ragnar and got stuck on login screen. no reactions, just can move my mouse cursor, no more. 

**Desktop**
 - Arch linux

**Comment by cococry** [comment]
make sure you got alacritty (or the terminal you configured for ragnar) installed (sudo pacman -S alacritty) and then press super + enter to open a terminal. also, you may have BAR_START_MONITOR set to 1 even though you only got a single monitor. So set that to 0 to see the bar.

**Comment by cebem1nt** [comment]
> make sure you got alacritty (or the terminal you configured for ragnar) installed (sudo pacman -S alacritty) and then press super + enter to open a terminal. also, you may have BAR_START_MONITOR set to 1 even though you only got a single monitor. So set that to 0 to see the bar. 

Yes, I have allacritty, and it is configured in config.h, as well as the bar and monitors. After login, Ragnar doesn't even start. I get stuck on sddm

**Comment by cococry** [comment]
ahh, now i get want your problem is, i don't know much about sddm but there should probably be a selection somewhere of which wm/de to start into. you should see ragnar in this selection. but to really make sure that you can start ragnar, try booting into your machine without starting your displaying manager and on the tty, create a (or edit the) .xinitrc and paste exec ragnar into it. then execute startx from the tty and ragnar will start.

**Comment by cebem1nt** [comment]
Rutina manually from tty worked, thx
