### ISSUE TITLE
Cant start ragnar in Xephyr

### ISSUE THREAD

**Issue by Sigmanificient** [cococry/Ragnar#9]
**Describe the bug**
Cant start ragnar in Xephyr.

**To Reproduce**
- compile ragnar
- start the `run` script.

**Expected behavior**
Ragnar should start within the Xephyr window

**Screenshots**
![image](https://github.com/cococry/Ragnar/assets/53050011/dbf2b352-c708-4770-9ac4-a170f5668c56)

**Desktop (please complete the following information):**
 - OS: NixOS
 To reproduce:
> `nix-shell -p gcc gnumake xorg.libX11 xorg.libXft xorg.libXfont xorg.libXcursor -I nixpkgs=channel:nixos-22.05`

**Comment by cococry** [comment]
its probably black because you have no wallpaper set. install alacritty to your system and press super + enter. this will start alacritty. Be aware the super + enter combination may not be used by your current window manager. 

And to set a wallpaper, i suggest using nitrogen with nitrogen --restore in .xinitrc
